apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    name: {{ .Release.Name }}
spec:
  selector:
    name: {{ .Release.Name }}
  ports:
    - name: control
      port: 5679