# Default values for onos-ztp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: onosproject/onos-ztp
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "onos-ztp"

debug: false

ingress:
  enabled: false

resources: {}

service:
  type: ClusterIP

nodeSelector: {}

tolerations: []

affinity: {}
