apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: partitions.cloud.atomix.io
spec:
  group: cloud.atomix.io
  names:
    kind: Partition
    listKind: PartitionList
    plural: partitions
    singular: partition
  scope: Namespaced
  version: v1beta1
  subresources:
    status: {}